[package]
name = "clap-js"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.5.56", features = ["string"] }
delegate = "0.13.5"
wasm-bindgen = "0.2.108"
